/* Generated By:JavaCC: Do not edit this line. FOLParserConstants.java */
package de.dominicscheurer.fol.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FOLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int CLOSE = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int NEG = 10;
  /** RegularExpression Id. */
  int CONJ = 11;
  /** RegularExpression Id. */
  int DISJ = 12;
  /** RegularExpression Id. */
  int IMP = 13;
  /** RegularExpression Id. */
  int ALL = 14;
  /** RegularExpression Id. */
  int EXIST = 15;
  /** RegularExpression Id. */
  int VARIABLE = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int INNER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int LOWER = 20;
  /** RegularExpression Id. */
  int UPPER = 21;
  /** RegularExpression Id. */
  int UNDER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
    "\"forall\"",
    "\"exists\"",
    "<VARIABLE>",
    "<ID>",
    "<INNER>",
    "<DIGIT>",
    "<LOWER>",
    "<UPPER>",
    "\"_\"",
  };

}
